workflows:
  terraform-basic:
    plan:
      steps:
        - run: terraform init
        - run: terraform plan -no-color -input=false -out $PLANFILE
    apply:
      steps:
        - run: terraform apply -no-color -input=false -compact-warnings -auto-approve $PLANFILE
