workflows:
  terraform-basic:
    plan:
      steps:
        - run: terraform init
        - run: terraform plan -no-color -input=false -out $PLANFILE
    apply:
      steps:
        - run: terraform apply -no-color -input=false -compact-warnings -auto-approve $PLANFILE

  terragrunt-basic:
    plan:
      steps:
        - run: terragrunt fmt -no-color -check=true -diff=true -write=false
        - run: terragrunt hclfmt --terragrunt-check
        - run: terragrunt plan -no-color -out $PLANFILE
    apply:
      steps:
        - run: terragrunt apply -no-color -input=false -compact-warnings -auto-approve $PLANFILE

  terragrunt-basic-with-asdf:
    asdf:
      enabled: true
    plan:
      steps:
        - run: terragrunt fmt -no-color -check=true -diff=true -write=false
        - run: terragrunt hclfmt --terragrunt-check
        - run: terragrunt plan -no-color -out $PLANFILE
    apply:
      steps:
        - run: terragrunt apply -no-color -input=false -compact-warnings -auto-approve $PLANFILE

  terragrunt-basic-check-with-asdf:
    asdf:
      enabled: true
    plan:
      steps:
        - run: terragrunt fmt -no-color -check=true -diff=true -write=false
        - run: terragrunt hclfmt --terragrunt-check
        # Create fake terraform-plan...
        - run: terragrunt show -json > $PLANFILE
    apply:
      steps:
        # fake successful apply to avoid `not automerging because project at dir "", workspace "default" has status "planned"` error
        - run: "echo 'This is CHECK-ONLY workflow - run `terragrunt apply` manually'"

  terragrunt-basic-with-asdf-and-approval-config:
    asdf:
      enabled: true
    check_gitlab_approvals:
      enabled: true
    plan:
      steps:
        - run: terragrunt fmt -no-color -check=true -diff=true -write=false
        - run: terragrunt hclfmt --terragrunt-check
        - run: terragrunt plan -no-color -out $PLANFILE
    apply:
      steps:
        - run: terragrunt apply -no-color -input=false -compact-warnings -auto-approve $PLANFILE

  terragrunt-basic-with-asdf-for-external-repos-and-approval-config:
    asdf:
      enabled: true
    pull_gitlab_variables:
      enabled: true
    check_gitlab_approvals:
      enabled: true
    checkov:
      enabled: false
    plan:
      steps:
        - run: terragrunt fmt -no-color -check=true -diff=true -write=false
        - run: terragrunt hclfmt --terragrunt-check
        - run: terragrunt plan -no-color -out $PLANFILE
    apply:
      steps:
        - run: terragrunt apply -no-color -input=false -compact-warnings -auto-approve $PLANFILE
